// GENERATED by extract-reference.mjs from the onboarding design prototype (sha256 ca316799478a5a9e829eb45e2843b70cd32d17201d6b2967ecaea804c05b648c).
// Frozen reference for the parity check. Do not edit.
module.exports = class Reference {
  zoneDefs() {
    return [
      { id: 'cardio', label: 'Cardio', icon: 'M3 12h4l2-5 4 10 2-5h6' },
      { id: 'weights', label: 'Free weights', icon: 'M6 6v12M18 6v12M3 9v6M21 9v6M6 12h12' },
      { id: 'machines', label: 'Machines', icon: 'M6 3v18M18 3v18M6 8h12M6 13h12M6 18h12' },
      { id: 'functional', label: 'Functional', icon: 'M13 2 4 14h7l-1 8 9-12h-7z' },
      { id: 'studio', label: 'Yoga studio', icon: 'M12 2.5a2 2 0 1 0 0.01 0M4 20c3-3 13-3 16 0M12 7v7M6 10.5h12' },
    ];
  }

  // Isometric line drawing of the gym, as an ordered list of layers (back to front).
  build(s, ink) {
    const C = 0.8660254;
    const sizes = { small: [9, 6], medium: [11, 7], large: [13, 8] };
    const [W, D] = sizes[s.size || 'medium'];
    const F = s.floors || 1;
    const R = (W + D) * 0.5;
    const gap = R * 0.62 + 1.6;
    const wallH = 2.4;
    const park = s.facilities.includes('parking');
    const xmin = -1.8, xmax = W + (park ? 5.4 : 1.6), ymin = -1.8, ymax = D + 1.8;
    const topU = (F - 1) * gap + wallH + 2.2;
    const wU = ((xmax - ymin) - (xmin - ymax)) * C;
    const hU = ((xmax + ymax) - (xmin + ymin)) * 0.5 + topU;
    const sc = Math.min(30, 740 / wU, 760 / hU);
    const minX = (xmin - ymax) * C, maxX = (xmax - ymin) * C;
    const minY = (xmin + ymin) * 0.5 - topU, maxY = (xmax + ymax) * 0.5;
    const ox = 420 - ((minX + maxX) / 2) * sc;
    const oy = 450 - ((minY + maxY) / 2) * sc;
    const n1 = (v) => v.toFixed(1);
    const P = (x, y, z) => [ox + (x - y) * C * sc, oy + ((x + y) * 0.5 - z) * sc];
    const f = (q) => n1(q[0]) + ' ' + n1(q[1]);
    const poly = (pts) => 'M' + pts.map((q) => f(P(q[0], q[1], q[2]))).join('L') + 'Z';
    const seg = (a, b) => 'M' + f(P(a[0], a[1], a[2])) + 'L' + f(P(b[0], b[1], b[2]));
    const box = (x, y, z, w, d, h) =>
      poly([[x, y, z + h], [x + w, y, z + h], [x + w, y + d, z + h], [x, y + d, z + h]]) +
      poly([[x + w, y, z], [x + w, y + d, z], [x + w, y + d, z + h], [x + w, y, z + h]]) +
      poly([[x, y + d, z], [x + w, y + d, z], [x + w, y + d, z + h], [x, y + d, z + h]]);
    const wire = (x, y, z, w, d, h) => {
      const c = [[x, y], [x + w, y], [x + w, y + d], [x, y + d]];
      let out = '';
      for (let i = 0; i < 4; i++) {
        const a = c[i], b = c[(i + 1) % 4];
        out += seg([a[0], a[1], z], [b[0], b[1], z]) + seg([a[0], a[1], z + h], [b[0], b[1], z + h]) + seg([a[0], a[1], z], [a[0], a[1], z + h]);
      }
      return out;
    };
    const ring = (fn, n = 28) => {
      const pts = [];
      for (let i = 0; i < n; i++) pts.push(fn((i / n) * Math.PI * 2));
      return poly(pts);
    };
    const ringH = (cx, cy, z, r) => ring((t) => [cx + r * Math.cos(t), cy + r * Math.sin(t), z]);
    const ringX = (x, cy, cz, r) => ring((t) => [x, cy + r * Math.cos(t), cz + r * Math.sin(t)]);
    const ringY = (cx, y, cz, r) => ring((t) => [cx + r * Math.cos(t), y, cz + r * Math.sin(t)]);
    const circ = (cx, cy, r) => 'M' + n1(cx - r) + ' ' + n1(cy) + 'a' + n1(r) + ' ' + n1(r) + ' 0 1 0 ' + n1(2 * r) + ' 0a' + n1(r) + ' ' + n1(r) + ' 0 1 0 ' + n1(-2 * r) + ' 0';
    const figure = (x, y, z) => {
      const [fx, fy] = P(x, y, z);
      const u = sc;
      const r = 0.17 * u, hy = fy - 1.57 * u;
      return 'M' + n1(fx - 0.09 * u) + ' ' + n1(fy) + 'L' + n1(fx - 0.11 * u) + ' ' + n1(fy - 0.76 * u) +
        'M' + n1(fx + 0.09 * u) + ' ' + n1(fy) + 'L' + n1(fx + 0.11 * u) + ' ' + n1(fy - 0.76 * u) +
        'M' + n1(fx - 0.2 * u) + ' ' + n1(fy - 0.74 * u) + 'L' + n1(fx - 0.24 * u) + ' ' + n1(fy - 1.32 * u) +
        'L' + n1(fx + 0.24 * u) + ' ' + n1(fy - 1.32 * u) + 'L' + n1(fx + 0.2 * u) + ' ' + n1(fy - 0.74 * u) + 'Z' +
        circ(fx, hy, r);
    };

    const layers = [];
    const add = (d, o = {}) => layers.push({
      d, fill: o.fill ?? '#fff', w: o.w ?? 1.25, dash: o.dash ?? 'none', op: o.op ?? 1,
      stroke: ink, txt: o.txt ?? '', tf: o.tf ?? '', fs: o.fs ?? 0, anchor: o.anchor ?? 'start',
    });
    const solidSize = !!s.size;
    const sz = solidSize ? {} : { dash: '5 5', op: 0.7 };

    // Site, dimension lines, trees
    add(poly([[xmin, ymin, -0.3], [xmax, ymin, -0.3], [xmax, ymax, -0.3], [xmin, ymax, -0.3]]), { fill: 'none', dash: '2 6', w: 0.8, op: 0.55 });
    const topZ = (F - 1) * gap + wallH;
    let dims = seg([0, D + 1.1, -0.3], [W, D + 1.1, -0.3]) + seg([0, D + 0.2, -0.3], [0, D + 1.5, -0.3]) + seg([W, D + 0.2, -0.3], [W, D + 1.5, -0.3]) +
      seg([-0.2, D + 1.3, -0.3], [0.2, D + 0.9, -0.3]) + seg([W - 0.2, D + 1.3, -0.3], [W + 0.2, D + 0.9, -0.3]) +
      seg([-1.1, 0, -0.3], [-1.1, D, -0.3]) + seg([-0.2, 0, -0.3], [-1.5, 0, -0.3]) + seg([-0.2, D, -0.3], [-1.5, D, -0.3]) +
      seg([-1.3, -0.2, -0.3], [-0.9, 0.2, -0.3]) + seg([-1.3, D - 0.2, -0.3], [-0.9, D + 0.2, -0.3]) +
      seg([-1.1, D + 1.1, -0.3], [-1.1, D + 1.1, topZ]);
    for (let k = 0; k < F; k++) dims += seg([-1.3, D + 1.1, k * gap], [-0.9, D + 1.1, k * gap]);
    dims += seg([-1.3, D + 1.1, topZ], [-0.9, D + 1.1, topZ]);
    add(dims, { fill: 'none', w: 0.75, op: 0.8 });
    if (s.city.trim()) {
      for (const [tx, ty] of [[W * 0.28, -1.0], [W * 0.62, -1.1]]) {
        const [cx, cy] = P(tx, ty, 1.95);
        add(seg([tx, ty, 0], [tx, ty, 1.15]) + circ(cx, cy, 0.8 * sc));
      }
    }

    // Where each zone goes: spread evenly over the floors, 3 x 2 cells per floor
    const gx0 = 1.3, gx1 = W - 0.3, gy0 = 0.5, gy1 = D - 0.3;
    const cw = (gx1 - gx0) / 3, cd = (gy1 - gy0) / 2;
    const cellAt = (k, i) => ({ x: gx0 + (i % 3) * cw, y: gy0 + Math.floor(i / 3) * cd, z: k * gap, k });
    const sel = this.zoneDefs().map((z) => z.id).filter((id) => s.zones.includes(id));
    const q = Math.max(1, Math.ceil(sel.length / F));
    const slots = (k) => (k === 0 ? [0, 1, 2, 3, 4] : [0, 1, 2, 3, 4, 5]);
    const where = {};
    const used = Array.from({ length: F }, () => ({}));
    for (let k = 0; k < F; k++) {
      sel.slice(k * q, (k + 1) * q).forEach((id, j) => {
        const slot = slots(k)[j];
        where[id] = cellAt(k, slot);
        used[k][slot] = id;
      });
    }
    const desk = cellAt(0, 5);

    // Per-floor objects, painted back to front by depth (x + y)
    const objs = Array.from({ length: F }, () => []);
    const put = (k, key, d, o = {}) => objs[k].push({ key, d, o });
    const tags = [];

    const zoneDraw = {
      cardio: (c) => {
        const n = Math.max(1, Math.min(3, Math.floor((cw - 0.2) / 1.3)));
        const tot = n * 0.9 + (n - 1) * 0.4;
        const ty = c.y + (cd - 1.9) / 2;
        for (let i = 0; i < n; i++) {
          const tx = c.x + (cw - tot) / 2 + i * 1.3;
          put(c.k, tx + ty + 1, box(tx, ty, c.z, 0.9, 1.9, 0.22));
          put(c.k, tx + ty + 1.01,
            seg([tx + 0.1, ty + 0.2, c.z + 0.22], [tx + 0.1, ty + 0.2, c.z + 1.2]) + seg([tx + 0.8, ty + 0.2, c.z + 0.22], [tx + 0.8, ty + 0.2, c.z + 1.2]) +
            seg([tx + 0.1, ty + 0.2, c.z + 0.95], [tx + 0.1, ty + 0.75, c.z + 0.95]) + seg([tx + 0.8, ty + 0.2, c.z + 0.95], [tx + 0.8, ty + 0.75, c.z + 0.95]) +
            box(tx + 0.02, ty + 0.06, c.z + 1.15, 0.86, 0.3, 0.16));
        }
      },
      weights: (c) => {
        const rx = c.x + 0.3, ry = c.y + 0.25;
        put(c.k, rx + ry + 1, wire(rx, ry, c.z, 1.4, 1.1, 2.3), { fill: 'none' });
        put(c.k, rx + ry + 1.2, seg([rx - 0.25, ry + 0.75, c.z + 1.45], [rx + 1.65, ry + 0.75, c.z + 1.45]));
        put(c.k, rx + ry + 1.3, ringX(rx + 0.0, ry + 0.75, c.z + 1.45, 0.42));
        put(c.k, rx + ry + 1.31, ringX(rx + 1.45, ry + 0.75, c.z + 1.45, 0.42));
        const bd = Math.max(0.7, Math.min(1.2, cd - 1.75));
        put(c.k, rx + ry + 2.5, box(rx + 0.48, ry + 1.35, c.z, 0.45, bd, 0.42));
        if (cw > 2.9) {
          const dx = c.x + cw - 0.9;
          let bells = box(dx, c.y + 0.3, c.z, 0.55, cd - 0.6, 0.6);
          for (let yy = c.y + 0.55; yy < c.y + cd - 0.5; yy += 0.45) bells += ringH(dx + 0.27, yy, c.z + 0.68, 0.12);
          put(c.k, dx + c.y + cd / 2, bells);
        }
      },
      machines: (c) => {
        const n = Math.max(1, Math.min(2, Math.floor((cw - 0.2) / 1.5)));
        for (let i = 0; i < n; i++) {
          const mx = c.x + 0.35 + i * 1.5, my = c.y + 0.25;
          let tower = box(mx, my, c.z, 0.8, 0.5, 2.3);
          for (let zz = 0.35; zz < 1.5; zz += 0.16) tower += seg([mx + 0.22, my + 0.5, c.z + zz], [mx + 0.58, my + 0.5, c.z + zz]);
          put(c.k, mx + my + 0.5, tower);
          put(c.k, mx + my + 0.6, seg([mx + 0.4, my + 0.5, c.z + 2.2], [mx + 0.4, my + 1.15, c.z + 1.1]));
          put(c.k, mx + my + 1.4, box(mx + 0.1, my + 1.0, c.z + 0.45, 0.6, 0.12, 0.85));
          put(c.k, mx + my + 1.6, box(mx + 0.1, my + 1.1, c.z, 0.6, 0.75, 0.45));
        }
      },
      functional: (c) => {
        const td = Math.min(1.3, cd * 0.45);
        put(c.k, c.x + c.y, poly([[c.x + 0.15, c.y + 0.25, c.z + 0.02], [c.x + cw - 0.15, c.y + 0.25, c.z + 0.02], [c.x + cw - 0.15, c.y + 0.25 + td, c.z + 0.02], [c.x + 0.15, c.y + 0.25 + td, c.z + 0.02]]));
        put(c.k, c.x + c.y + 0.01, seg([c.x + 0.4, c.y + 0.25 + td / 2, c.z + 0.02], [c.x + cw - 0.4, c.y + 0.25 + td / 2, c.z + 0.02]), { fill: 'none', dash: '4 4', w: 0.8 });
        const bx = c.x + 0.35, by = c.y + cd - 1.15;
        put(c.k, bx + by + 1, box(bx, by, c.z, 0.9, 0.8, 0.55));
        put(c.k, bx + by + 1.1, box(bx + 0.12, by + 0.1, c.z + 0.55, 0.66, 0.6, 0.4));
        const tx = c.x + cw - 0.85, ty = c.y + cd - 0.75;
        put(c.k, tx + ty, ringH(tx, ty, c.z, 0.52) + ringH(tx, ty, c.z + 0.28, 0.52));
        put(c.k, tx + ty + 0.01, ringH(tx, ty, c.z + 0.28, 0.24), { fill: 'none' });
      },
      studio: (c) => {
        const n = Math.max(1, Math.min(4, Math.floor((cw - 0.1) / 0.95)));
        const md = Math.min(1.8, cd - 0.8);
        for (let i = 0; i < n; i++) {
          const mx = c.x + 0.25 + i * 0.95;
          put(c.k, mx + c.y, box(mx, c.y + 0.3, c.z, 0.7, md, 0.05));
        }
        const [bx, by] = P(c.x + cw - 0.5, c.y + cd - 0.45, c.z + 0.38);
        put(c.k, c.x + cw + c.y + cd, circ(bx, by, 0.38 * sc) + ringH(c.x + cw - 0.5, c.y + cd - 0.45, c.z + 0.38, 0.38));
      },
    };

    for (let k = 0; k < F; k++) {
      for (const i of slots(k)) {
        if (used[k][i]) continue;
        const c = cellAt(k, i);
        put(k, -100, poly([[c.x + 0.15, c.y + 0.15, c.z + 0.01], [c.x + cw - 0.15, c.y + 0.15, c.z + 0.01], [c.x + cw - 0.15, c.y + cd - 0.15, c.z + 0.01], [c.x + 0.15, c.y + cd - 0.15, c.z + 0.01]]), { fill: 'none', dash: '3 5', w: 0.75, op: 0.6 });
      }
    }
    for (const id of sel) zoneDraw[id](where[id]);

    if (s.facilities.includes('lockers')) {
      const y0 = 0.6, y1 = D / 2 - 0.15;
      let d = box(0.3, y0, 0, 0.55, y1 - y0, 1.9);
      for (let yy = y0 + 0.5; yy < y1 - 0.1; yy += 0.5) d += seg([0.85, yy, 0], [0.85, yy, 1.9]);
      put(0, 0.6 + (y0 + y1) / 2, d);
    }
    if (s.facilities.includes('showers')) {
      for (let i = 0; i < 2; i++) {
        const sy = D / 2 + 0.15 + i * 1.0;
        if (sy + 0.9 > D - 0.2) break;
        put(0, 0.6 + sy + 0.4, poly([[0.3, sy, 0.02], [1.1, sy, 0.02], [1.1, sy + 0.9, 0.02], [0.3, sy + 0.9, 0.02]]) + wire(0.3, sy, 0, 0.8, 0.9, 2.0) + seg([0.35, sy + 0.45, 1.9], [0.65, sy + 0.45, 1.75]), { fill: 'none' });
      }
    }

    if (s.staff != null) {
      const n = Math.max(1, Math.min(3, s.staff));
      for (let i = 0; i < n; i++) {
        const fx = desk.x + 0.6 + i * 0.75, fy = desk.y + 0.45;
        put(0, fx + fy, figure(fx, fy, 0));
      }
      put(0, desk.x + desk.y + 1.6, box(desk.x + 0.3, desk.y + 0.95, 0, cw - 0.6, 0.5, 1.0));
      put(0, desk.x + desk.y + 1.7, box(desk.x + 0.7, desk.y + 0.98, 1.0, 0.45, 0.06, 0.4));
    } else {
      put(0, -100, poly([[desk.x + 0.15, desk.y + 0.15, 0.01], [desk.x + cw - 0.15, desk.y + 0.15, 0.01], [desk.x + cw - 0.15, desk.y + cd - 0.15, 0.01], [desk.x + 0.15, desk.y + cd - 0.15, 0.01]]), { fill: 'none', dash: '3 5', w: 0.75, op: 0.6 });
    }

    const perCell = {};
    s.trainers.slice(0, 6).forEach((t) => {
      const c = where[t.spec] || desk;
      const ck = c.k + ':' + c.x + ':' + c.y;
      const j = perCell[ck] = (perCell[ck] ?? -1) + 1;
      const tx = c.x + 0.45 + (j % 3) * 0.8, ty = c.y + cd - 0.3 - Math.floor(j / 3) * 0.6;
      put(c.k, tx + ty + 0.5, figure(tx, ty, c.z));
      const [hx, hy] = P(tx, ty, c.z + 1.95);
      const tw = t.name.length * 7.4 + 6;
      tags.push({ d: 'M' + n1(hx) + ' ' + n1(hy) + 'l14 -16h' + n1(tw), x: hx + 17, y: hy - 25, txt: t.name.toUpperCase() });
    });

    // Paint: floors bottom to top, parking after the ground floor
    for (let k = 0; k < F; k++) {
      const z0 = k * gap;
      if (k > 0) {
        let g = '';
        for (const [cx, cy] of [[0, D], [W, D], [W, 0]]) g += seg([cx, cy, z0 - gap + 0.01], [cx, cy, z0 - 0.3]);
        add(g, { fill: 'none', dash: '3 5', w: 0.75, op: 0.7 });
      }
      add(box(0, 0, z0 - 0.3, W, D, 0.3), sz);
      let back = box(0, 0, z0, W, 0.2, wallH);
      const wx0 = k === 0 ? 2.6 : 1.3, wx1 = k === 0 ? W - 2.6 : W - 0.8;
      for (let x = wx0; x + 1.2 <= wx1; x += 1.9) {
        back += poly([[x, 0.2, z0 + 0.9], [x + 1.2, 0.2, z0 + 0.9], [x + 1.2, 0.2, z0 + 2.0], [x, 0.2, z0 + 2.0]]) + seg([x + 0.6, 0.2, z0 + 0.9], [x + 0.6, 0.2, z0 + 2.0]);
      }
      if (k === 0) back += poly([[W - 2.0, 0.2, 0], [W - 1.0, 0.2, 0], [W - 1.0, 0.2, 2.0], [W - 2.0, 0.2, 2.0]]) + seg([W - 1.2, 0.2, 0.95], [W - 1.2, 0.2, 1.1]);
      if (k === 0 && s.hours) {
        back += ringY(1.5, 0.2, 1.55, 0.38) + seg([1.5, 0.2, 1.55], [1.5, 0.2, 1.82]) + seg([1.5, 0.2, 1.55], [1.7, 0.2, 1.45]);
        if (s.hours === '24') back += ringY(1.5, 0.2, 1.55, 0.48);
      }
      add(back, sz);
      let left = box(0, 0, z0, 0.2, D, wallH);
      for (let y = 1.3; y + 1.2 <= D - 0.6; y += 1.9) {
        if (k === 0 && (s.facilities.includes('lockers') || s.facilities.includes('showers'))) break;
        left += poly([[0.2, y, z0 + 0.9], [0.2, y + 1.2, z0 + 0.9], [0.2, y + 1.2, z0 + 2.0], [0.2, y, z0 + 2.0]]) + seg([0.2, y + 0.6, z0 + 0.9], [0.2, y + 0.6, z0 + 2.0]);
      }
      add(left, sz);

      if (k === F - 1) {
        const sx0 = W * 0.18, sx1 = W * 0.82, sz0 = z0 + wallH + 0.55, sz1 = sz0 + 1.25;
        const has = !!s.gymName.trim();
        add(seg([W * 0.3, 0.1, z0 + wallH], [W * 0.3, 0.1, sz0]) + seg([W * 0.7, 0.1, z0 + wallH], [W * 0.7, 0.1, sz0]), { fill: 'none' });
        add(box(sx0, 0, sz0, sx1 - sx0, 0.18, sz1 - sz0), has ? {} : { dash: '4 4', op: 0.7 });
        const name = s.gymName.trim().toUpperCase();
        const [tx, ty] = P((sx0 + sx1) / 2, 0.18, (sz0 + sz1) / 2);
        const fs = Math.min(0.62 * sc, ((sx1 - sx0) * sc * 0.88) / (Math.max(5, name.length) * 0.68));
        add('', { txt: name, tf: 'matrix(' + C + ' 0.5 0 1 ' + n1(tx) + ' ' + n1(ty) + ')', fs: n1(fs), anchor: 'middle' });
      }

      objs[k].sort((a, b) => a.key - b.key).forEach((ob) => add(ob.d, ob.o));

      if (k === 0 && park) {
        const px0 = W + 1.3, px1 = W + 4.9;
        let lot = poly([[px0, 0.3, 0], [px1, 0.3, 0], [px1, D - 0.3, 0], [px0, D - 0.3, 0]]);
        for (let y = 0.3 + 2.0; y < D - 0.6; y += 2.0) lot += seg([px0, y, 0], [px1, y, 0]);
        add(lot, { fill: 'none', dash: '4 4', w: 0.8 });
        const cars = Math.min(2, Math.floor((D - 0.6) / 2.0));
        for (let i = 0; i < cars; i++) {
          const cx = px0 + 0.5, cy = 0.3 + i * 2.0 + 0.35;
          add(box(cx, cy, 0.15, 2.6, 1.3, 0.5) + ringX(cx + 2.6, cy + 0.3, 0.25, 0.01));
          add(box(cx + 0.65, cy + 0.12, 0.65, 1.25, 1.06, 0.42));
          add(ringY(cx + 0.55, cy + 1.3, 0.25, 0.25) + ringY(cx + 2.05, cy + 1.3, 0.25, 0.25));
        }
      }
    }

    tags.forEach((t) => add(t.d, { fill: 'none', w: 0.75, txt: t.txt, tf: 'translate(' + n1(t.x) + ' ' + n1(t.y) + ')', fs: 11 }));
    return layers;
  }


};
