"""leads

Revision ID: 7ac8a48a204c
Revises: 2863737b5570
Create Date: 2026-10-01 23:20:57.425570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db


# revision identifiers, used by Alembic.
revision: str = '7ac8a48a204c'
down_revision: Union[str, Sequence[str], None] = '2863737b5570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('walk_in', 'phone_call', 'instagram', 'facebook', 'google', 'referral', 'website', 'other', name='leadsource', native_enum=False, length=20), nullable=False),
    sa.Column('stage', sa.Enum('new', 'contacted', 'trial_booked', 'trial_done', 'converted', 'lost', name='leadstage', native_enum=False, length=20), nullable=False),
    sa.Column('interest', sa.String(length=300), nullable=True),
    sa.Column('interested_plan_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('next_follow_up_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('trial_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_member_id', sa.Uuid(), nullable=True),
    sa.Column('converted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('stage_changed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_leads_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_member_id'], ['members.id'], name=op.f('fk_leads_converted_member_id_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_leads_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interested_plan_id'], ['plans.id'], name=op.f('fk_leads_interested_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_leads_gym_id_phone', ['gym_id', 'phone'], unique=False)
        batch_op.create_index('ix_leads_gym_id_stage', ['gym_id', 'stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_next_follow_up_at'), ['next_follow_up_at'], unique=False)

    op.create_table('lead_activities',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('created', 'note', 'call', 'whatsapp', 'visit', 'stage', 'converted', name='activitykind', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lead_activities_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_lead_activities_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_activities_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_activities'))
    )
    with op.batch_alter_table('lead_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_activities_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activities_lead_id'), ['lead_id'], unique=False)

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_form_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_gyms_lead_form_token'), ['lead_form_token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_gyms_lead_form_token'), type_='unique')
        batch_op.drop_column('lead_form_token')

    with op.batch_alter_table('lead_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_activities_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activities_gym_id'))

    op.drop_table('lead_activities')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_next_follow_up_at'))
        batch_op.drop_index('ix_leads_gym_id_stage')
        batch_op.drop_index('ix_leads_gym_id_phone')
        batch_op.drop_index(batch_op.f('ix_leads_gym_id'))
        batch_op.drop_index(batch_op.f('ix_leads_assigned_to'))

    op.drop_table('leads')
    # ### end Alembic commands ###
