"""reminders notifications gym reminder settings

Revision ID: 1bd8999a3a2d
Revises: 8315cdd2ba7f
Create Date: 2026-10-01 22:14:54.220835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd8999a3a2d'
down_revision: Union[str, Sequence[str], None] = '8315cdd2ba7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_notifications_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name=op.f('uq_notifications_user_id'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('reminder_logs',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='channel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='sendstatus', native_enum=False, length=20), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('sent_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_reminder_logs_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_reminder_logs_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_reminder_logs_membership_id_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_reminder_logs_sent_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_logs')),
    sa.UniqueConstraint('membership_id', 'offset_days', 'channel', name=op.f('uq_reminder_logs_membership_id'))
    )
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_logs_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_logs_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_logs_membership_id'), ['membership_id'], unique=False)

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminders_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('reminder_hour', sa.Integer(), server_default='9', nullable=False))
        batch_op.add_column(sa.Column('reminder_templates', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('reminder_templates')
        batch_op.drop_column('reminder_hour')
        batch_op.drop_column('reminders_enabled')

    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_logs_membership_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_logs_member_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_logs_gym_id'))

    op.drop_table('reminder_logs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_gym_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
