"""gym onboarding

Revision ID: f8e41a7005b5
Revises: 5e6ef883d30c
Create Date: 2026-10-05 10:54:57.502742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db


# revision identifiers, used by Alembic.
revision: str = 'f8e41a7005b5'
down_revision: Union[str, Sequence[str], None] = '5e6ef883d30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed_at', app.core.db.UTCDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###
    # Gyms that exist today are already set up; only gyms created from now on see the wizard.
    op.execute(sa.text("UPDATE gyms SET onboarding_completed_at = created_at"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed_at')
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
