"""import jobs

Revision ID: 217b96d25d8f
Revises: a6bba5f41406
Create Date: 2026-10-02 15:13:58.723956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db


# revision identifiers, used by Alembic.
revision: str = '217b96d25d8f'
down_revision: Union[str, Sequence[str], None] = 'a6bba5f41406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('entity', sa.Enum('members', 'leads', 'payments', 'checkups', 'plans', name='importentity', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'ready', 'running', 'done', 'failed', name='importstatus', native_enum=False, length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('duplicate_mode', sa.Enum('skip', 'update', name='duplicatemode', native_enum=False, length=20), nullable=False),
    sa.Column('date_order', sa.Enum('dmy', 'mdy', 'ymd', name='dateorder', native_enum=False, length=20), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_file_key', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('finished_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_import_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_import_jobs_gym_id_gyms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_gym_id'), ['gym_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_gym_id'))

    op.drop_table('import_jobs')
    # ### end Alembic commands ###
