"""finance payments expenses

Revision ID: a6bba5f41406
Revises: 7ac8a48a204c
Create Date: 2026-10-02 14:25:21.152361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db


# revision identifiers, used by Alembic.
revision: str = 'a6bba5f41406'
down_revision: Union[str, Sequence[str], None] = '7ac8a48a204c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('rent', 'salaries', 'utilities', 'equipment', 'maintenance', 'marketing', 'supplies', 'software', 'taxes', 'other', name='expensecategory', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('method', sa.Enum('cash', 'upi', 'card', 'bank_transfer', 'cheque', 'other', name='paymentmethod', native_enum=False, length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attachment_key', sa.String(length=300), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_expenses_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_expenses_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_expenses_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_expenses_gym_id_spent_on', ['gym_id', 'spent_on'], unique=False)

    op.create_table('payments',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'upi', 'card', 'bank_transfer', 'cheque', 'other', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('receipt_no', sa.String(length=30), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('voided_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('voided_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_payments_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_payments_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_payments_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_payments_recorded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_payments_voided_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('gym_id', 'receipt_no', name=op.f('uq_payments_gym_id'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_payments_gym_id_paid_on', ['gym_id', 'paid_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_membership_id'), ['membership_id'], unique=False)

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_counter', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('receipt_counter')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_membership_id'))
        batch_op.drop_index(batch_op.f('ix_payments_member_id'))
        batch_op.drop_index('ix_payments_gym_id_paid_on')
        batch_op.drop_index(batch_op.f('ix_payments_gym_id'))

    op.drop_table('payments')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_gym_id_spent_on')
        batch_op.drop_index(batch_op.f('ix_expenses_gym_id'))

    op.drop_table('expenses')
    # ### end Alembic commands ###
